name: APK Downloader

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Package name (e.g., org.telegram.messenger)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  download-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download apkeep
        run: |
          wget -q https://github.com/EFForg/apkeep/releases/latest/download/apkeep-x86_64-unknown-linux-gnu -O apkeep
          chmod +x apkeep

      - name: Fetch APK
        run: |
          mkdir -p downloads
          ./apkeep -a ${{ inputs.package_name }} -d apk-pure downloads/

      - name: Process and Split
        run: |
          cd temp_dl
          DOWNLOADED_FILE=$(ls -1A | head -n 1)
          
          if [ -z "$DOWNLOADED_FILE" ]; then
            echo "Error: Downloaded file not found."
            exit 1
          fi

          mkdir -p ../apks
          7z a -mx=3 -v85m "../apks/${{ inputs.package_name }}.7z" "$DOWNLOADED_FILE"
          
          cd ..
          rm -rf temp_dl

      - name: Commit and Push
        run: |
          git config user.name "NET-Sentinel Bot"
          git config user.email "224584266+NetSentinel-Bot@users.noreply.github.com"
          git add apks/
          git commit -m "Add ${{ inputs.package_name }}" || echo "No changes to commit"
          git push
